### ISSUE TITLE
ja-netfilter-modified

### ISSUE THREAD

**Issue by technikker** [v-JiangNan/Aliyun-ACA-AI#1]
Hi, sorry for doing this here, not sure how else to contact you.

https://github.com/v-JiangNan/ja-netfilter-modified

How to you use 'generate_key.py' to make new activation code?  The keys it generates don't work for me (invalid key)

**Comment by technikker** [comment]
Google 翻译（我不懂中文）

嗨，抱歉在这里这样做，不知道还有什么其他方法可以联系到你。

https://github.com/v-JiangNan/ja-netfilter-modified

如何使用“generate_key.py”制作新的激活码？它生成的密钥对我不起作用（无效密钥）

**Comment by v-JiangNan** [comment]
> Hi, sorry for doing this here, not sure how else to contact you.
> 
> https://github.com/v-JiangNan/ja-netfilter-modified
> 
> How to you use 'generate_key.py' to make new activation code? The keys it generates don't work for me (invalid key)

Thank you very much for your interest in the ja-netfilter-modified project. We regret to inform you that this project has been archived, and we are no longer able to provide technical support.

We recommend strictly follow the "**使用说明**" in the README file. If you encounter issues with activation, please consider exploring the solutions provided in the "**常见问题**" section. Regarding the issue you mentioned about the invalid key generated by `generate_key.py`, you may find helpful solutions in the links provided under the "**参考资料**" section.

Thank you for your understanding.

**Comment by technikker** [comment]
Thanks for your reply, I was able to figure it out after using google translate on the links in the "参考资料" section.  It all works now, and with a little extra code also works for other JetBrains IDEs.
